/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ClientsImport } from './routes/_clients'
import { Route as IndexImport } from './routes/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as ClientsClientsIndexImport } from './routes/_clients/clients/index'
import { Route as ClientsClientsClientIdImport } from './routes/_clients/clients/$clientId'

// Create/Update Routes

const ClientsRoute = ClientsImport.update({
  id: '/_clients',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const ClientsClientsIndexRoute = ClientsClientsIndexImport.update({
  path: '/clients/',
  getParentRoute: () => ClientsRoute,
} as any)

const ClientsClientsClientIdRoute = ClientsClientsClientIdImport.update({
  path: '/clients/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_clients': {
      preLoaderRoute: typeof ClientsImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/_clients/clients/$clientId': {
      preLoaderRoute: typeof ClientsClientsClientIdImport
      parentRoute: typeof ClientsImport
    }
    '/_clients/clients/': {
      preLoaderRoute: typeof ClientsClientsIndexImport
      parentRoute: typeof ClientsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ClientsRoute.addChildren([
    ClientsClientsClientIdRoute,
    ClientsClientsIndexRoute,
  ]),
  LoginIndexRoute,
  RegisterIndexRoute,
])

/* prettier-ignore-end */
