/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ClientsImport } from "./routes/_clients";
import { Route as IndexImport } from "./routes/index";
import { Route as RegisterIndexImport } from "./routes/register/index";
import { Route as LoginIndexImport } from "./routes/login/index";
import { Route as ClientsIndexImport } from "./routes/_clients/clients/index";

// Create/Update Routes

const ClientsRoute = ClientsImport.update({
  id: "/_clients",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const RegisterIndexRoute = RegisterIndexImport.update({
  path: "/register/",
  getParentRoute: () => rootRoute,
} as any);

const LoginIndexRoute = LoginIndexImport.update({
  path: "/login/",
  getParentRoute: () => rootRoute,
} as any);

const ClientsIndexRoute = ClientsIndexImport.update({
  path: "/clients/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/_clients": {
      preLoaderRoute: typeof ClientsImport;
      parentRoute: typeof rootRoute;
    };
    "/clients/": {
      preLoaderRoute: typeof ClientsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/login/": {
      preLoaderRoute: typeof LoginIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/register/": {
      preLoaderRoute: typeof RegisterIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ClientsRoute,
  ClientsIndexRoute,
  LoginIndexRoute,
  RegisterIndexRoute,
]);

/* prettier-ignore-end */
