/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedDashboardImport } from './routes/_protected/_dashboard'
import { Route as AuthRegisterIndexImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexImport } from './routes/_auth/login/index'
import { Route as ProtectedDashboardDashboardIndexImport } from './routes/_protected/_dashboard/dashboard/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedDashboardRoute = ProtectedDashboardImport.update({
  id: '/_protected/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/_auth/register/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/_auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedDashboardDashboardIndexRoute =
  ProtectedDashboardDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected/_dashboard': {
      preLoaderRoute: typeof ProtectedDashboardImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login/': {
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/register/': {
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected/_dashboard/dashboard/': {
      preLoaderRoute: typeof ProtectedDashboardDashboardIndexImport
      parentRoute: typeof ProtectedDashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ProtectedDashboardRoute.addChildren([ProtectedDashboardDashboardIndexRoute]),
  AuthLoginIndexRoute,
  AuthRegisterIndexRoute,
])

/* prettier-ignore-end */
